name: Build a JAR in spring boot using springboot
on:
  pull_request:
    types: [opened, synchronize, reopened]




jobs:
  build:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup-java
        uses: actions/setup-java@v4
        with:
          distribution: ‘jetbrains’
          java-version: '23'


      - name: Build with Maven
        run: mvn clean install



      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: java-app
          path: '${{ github.workspace }}/target/*.jar'


      - name: Run Tests
        run: mvn test

