name: Sub Workflow Build

on:
    workflow_call:
      inputs:
        config-path:
          required: true
          type: string
      secrets:
        token:
          required: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout
        uses: actions/checkout@v4


      - name: Setup-java
        uses: actions/setup-java@v4
        with:
          distribution: ‘jetbrains’
          java-version: '21'



      - name: Build with Maven
        run: |
          cd ${{ inputs.working_directory }}
          mvn clean install




      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: java-app
          path: '${{ inputs.working_directory }}/target/*.jar'


      - name: Run Tests
        run: |
          cd ${{ inputs.working_directory }}
          mvn test

