name: Build and Archive JDK Project

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up OpenJDK 23
        uses: actions/setup-java@v4
        with:
          java-version: '23'
          distribution: 'zulu'

      - name: Navigate to project folder
        working-directory: wap_api
        run: echo "Inside project folder $(pwd)"

      - name: Build project
        working-directory: wap_api
        run: mvn clean install

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: built-project
          path: wap_api/target/*.zip