name: Build and Archive JDK Project

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      MYSQL_DB_URL: ${{ secrets.MYSQL_DB_URL }}
      DB_USERNAME: ${{ secrets.DB_USERNAME }}
      DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: check environment variables
        run: |
          echo "DB URL: $MYSQL_DB_URL"
          echo "DB Username: $DB_USERNAME"
          echo "DB Password: $DB_PASSWORD"

      - name: Set up OpenJDK 23
        uses: actions/setup-java@v4
        with:
          java-version: '23'
          distribution: 'zulu'

      - name: Navigate to project folder
        working-directory: wap_api
        run: echo "Inside project folder $(pwd)"

      - name: Build project
        working-directory: wap_api
        run: mvn clean install

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: built-project
          path: wap_api/target/*.zip